### ISSUE TITLE
colours

### ISSUE THREAD

**Issue by mathjiajia** [sontungexpt/sttusline#1]
Is it possible to use bg of hl group `StatusLine` as the bg colour?

**Comment by sontungexpt** [comment]
> Is it possible to use bg of hl group `StatusLine` as the bg colour?

I don't quite understand your wish, can you explain it more clearly?

**Comment by mathjiajia** [comment]
could we override the colours defined in `./lua/sttusline/utils/color.lua`?

**Comment by sontungexpt** [comment]
> could we override the colours defined in `./lua/sttusline/utils/color.lua`?

"Unfortunately, it is currently not possible. The highlight support of this plugin is still quite simple because I'm in exam season. May I ask whether you would like to adjust the color of the default components you created or create your own component? This way, I can assist you further.

**Comment by mathjiajia** [comment]
Reason: the current bg is different from my statusline so it looks ugly.
I know that the colour for each component can be changed separately, but it will be great to set the colour in just one place.

Good luck with your exams

**Comment by sontungexpt** [comment]
> Reason: the current bg is different from my statusline so it looks ugly. I know that the colour for each component can be changed separately, but it will be great to set the colour in just one place.
> 
> Good luck with your exams

You can migrate to `table_version` branch to do this, it may take you a little time

**Comment by sontungexpt** [comment]
> Reason: the current bg is different from my statusline so it looks ugly. I know that the colour for each component can be changed separately, but it will be great to set the colour in just one place.
> Good luck with your exams

You can migrate to `table_version` branch to do this, it may take you a little time, this branch has more highlighting features than main branch, Hope you enjoy it!

**Comment by mathjiajia** [comment]
Thanks.
It looks nice.
