### ISSUE TITLE
`vim.loop` is deprecated

### ISSUE THREAD

**Issue by orumin** [sontungexpt/sttusline#7]
`vim.loop` is replaced with `vim.uv` in newer version.
see https://github.com/neovim/neovim/pull/22846

**Comment by orumin** [comment]
to support both older and newer version, do as below:
```lua
local uv = vim.uv or vim.loop
local uname = uv.os_uname()
...
```

**Comment by sontungexpt** [comment]
> to support both older and newer version, do as below:
> 
> ```lua
> local uv = vim.uv or vim.loop
> local uname = uv.os_uname()
> ...
> ```

Thanks for your reminding
